let list = [
];

// Autogenerated

function loadList() {
  const links = list.map((src, i) => ({
    id: `track-${i}`,
    href: `./tracks/${src}.spc`,
    title: src
  }));

  for (const link of links) {
    const track = document.createElement('div');
    track.innerHTML = link.title;
    track.onclick = async () => {
      const r = await fetch(link.href);
      const d = await r.arrayBuffer();
      loadSpc(new Uint8Array(d));
    }
    el('track-list').appendChild(track);
  }
}


