const fs = require('fs');
const path = require('path');

const tracksPath = path.join(__dirname, 'tracks');
const scriptPath = path.join(tracksPath, 'list.js');
const scriptLines = fs.readFileSync(scriptPath, 'utf-8').split('\n');
while (!scriptLines[0].includes('Autogenerated')) {
  scriptLines.shift();
}

const waves = fs.readdirSync(tracksPath).filter(f => f.endsWith('.spc'));
scriptLines.unshift(`let list = [\n${
  waves
    .map(w => `  "${w.replace(/\.spc$/i, '')}",\n`)
    .join('')
}];\n`);

fs.writeFileSync(scriptPath, scriptLines.join('\n'));
